minimumReleaseAgeExclude:
  - '@codingame/monaco-vscode-api@34.0.1'
  - '@codingame/monaco-vscode-base-service-override@34.0.1'
  - '@codingame/monaco-vscode-environment-service-override@34.0.1'
  - '@codingame/monaco-vscode-extension-api@34.0.1'
  - '@codingame/monaco-vscode-extensions-service-override@34.0.1'
  - '@codingame/monaco-vscode-files-service-override@34.0.1'
  - '@codingame/monaco-vscode-host-service-override@34.0.1'
  - '@codingame/monaco-vscode-layout-service-override@34.0.1'
  - '@codingame/monaco-vscode-quickaccess-service-override@34.0.1'
