language: node_js
node_js:
  - "8"
  - "10"
script: skip
jobs:
  include:
  - stage: deploy
    if: NOT type IN (cron, pull_request)
    os: linux
    node_js: '8'
    before_script: skip
    script: skip
    install: skip
    before_deploy:
      - |
        if ! [ "$BEFORE_DEPLOY_RUN" ]; then
          export BEFORE_DEPLOY_RUN=1
          printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" >> ~/.npmrc
          yarn
        fi
    deploy:
      - provider: script
        script: yarn run publish:next
        on:
          branch: master
        skip_cleanup: true
