language: node_js
node_js:
  - "6"
  - "7"
before_install:
  - npm i -g npm@latest
cache:
  directories:
    - node_modules
    - example/node_modules
install:
  - npm install
  - cd example
  - npm install