name: Build, Lint and Test

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: mise-en-place
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Install
        shell: bash
        run: |
          npm ci

      - name: Versions Report
        shell: bash
        run: |
          npm run report:versions

      - name: Build
        shell: bash
        run: |
          npm run build

      - name: Lint & Format
        shell: bash
        run: |
          npm run lint
          npm run fmt

      - name: Test
        shell: bash
        run: |
          npm run test:ci:tags

      - name: Publish Dry-Run
        # dry-run is always performed
        uses: TypeFox/gh-publish-npm@7f487ef219d953f46274fc1c67dfc835c53fbc11 # v0.3.3 / dev
        with:
          dry-run: true
          verbose: true
          npm-packages: |
            packages/client
            packages/vscode-ws-jsonrpc
            packages/wrapper-react
