name: Publish to npm

on:
  push:
    branches:
      - 'release-prep'
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Perform a dry run without publishing to npm'
        required: true
        default: true
        type: boolean
      npmTag:
        description: 'Use a tag for creating a pre-release'
        required: false
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: mise-en-place
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Install
        shell: bash
        run: |
          npm ci

      - name: Versions Report
        shell: bash
        run: |
          npm run report:versions

      - name: Build
        shell: bash
        run: |
          npm run build

      - name: Lint & Format
        shell: bash
        run: |
          npm run lint
          npm run fmt

      - name: Test
        shell: bash
        run: |
          npm run test:ci:tags

      - name: Publish
        uses: TypeFox/gh-publish-npm@b87a80818bdbc41d52c3aa2eec87b0e8379936f1 # v0.3.1
        with:
          dry-run: ${{ github.event.inputs.dryRun }}
          npm-tag: ${{ github.event.inputs.npmTag }}
          npm-packages: |
            packages/client
            packages/vscode-ws-jsonrpc
            packages/wrapper-react
