name: Verification Builds

on:
  push:
    branches:
      - 'verify'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: mise-en-place
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Install
        shell: bash
        run: |
          npm ci

      - name: Versions Report
        shell: bash
        run: |
          npm run report:versions

      - name: Execute verification
        shell: bash
        run: |
          bash ./verify/buildAll.sh
